rtmpdump: rtmp.cpp log.cpp AMFObject.cpp rtmppacket.cpp rtmpdump.cpp rtmp.h log.h AMFObject.h rtmppacket.h
	g++ -Wall rtmp.cpp log.cpp AMFObject.cpp rtmppacket.cpp rtmpdump.cpp -o rtmpdump -lboost_regex

